dashnor/urls.py
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('', include('files.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "files"

urlpatterns = [
    path('', views.index, name='index'),
    path('upload', views.upload, name="upload")
]

files/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
class File(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.FileField(upload_to=settings.MEDIA_ROOT +"/user_datas/", blank=True)

    def name(self):
        return self.name.replace('media/user_data/', '')

files/forms.py
from django import forms


class FilesUploadForm(forms.Form):
    files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

files/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import File
from .forms import FilesUploadForm


# Create your views here.
@login_required()
def index(request):
    files = File.objects.all().filter(user_id=request.user.id)
    return render(request, 'files/index.html', {'files': files})


@login_required()
def upload(request):
    if request.method == "POST":
        form = FilesUploadForm(request.POST, request.FILES)
        files = request.FILES.getlist('files')
        if form.is_valid():
            for f in files:
                file_instance = File(file=f, user_id=request.user.id)
                file_instance.save()
    else:
        form = FilesUploadForm()
    return render(request, 'files/upload.html', {'form': form})

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashnor {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<body>
<div class="container">
    {% block content %}

    {% endblock %}
</div>
{% block scripts %}

{% endblock %}
</body>
</html>

templates/files/index.html
{% extends 'base.html' %}

{% block title %}
    Manage Files
{% endblock %}

{% block content %}
    <header class="mt-5">
        <a href="{% url 'files:upload' %}" class="btn btn-primary">Upload Files</a>
        <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
    </header>
    <main>
        <table class="table table-stripe">
            <thead>
            <tr>
                <th>File Name</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for x in files %}
                <tr>
                    <td>{{ x.file }}</td>
                <td><a href="{{ x.file.url }}" download class="btn btn-primary">Download</a></td>
                </tr>
            {% empty %}
            <tr>
                <td colspan="2">No Files Found</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </main>
{% endblock %}

templates/files/upload.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'files:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h2>Upload files here</h2>
    <input type="file" multiple class="form-control my-3" name="files"/>
    <button class="btn btn-primary" type="submit">Submit</button>
    </form>
{% endblock %}